---
# tasks file for haproxy

# - name: Update repository
#   apt:
#     update_cache: yes

# - name: Install haproxy
#   apt:
#     name: haproxy
#     state: present
#     update_cache: yes

- name: Copy haproxy config file
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy