---
# tasks file for preinstall

- name: basic setup
  include_tasks: basic.yaml

- name: telegram notify
  include_tasks: telegram-notify.yaml

- name: setup time synchronization
  include_tasks: chrony.yaml